import pygame
from pyfiglet import Figlet
from time import sleep as wait
import os
pygame.init()
sample = pygame.mixer.Sound("res/sample.mp3")
music = pygame.mixer.Sound("res/music.mp3")
easter_egg_sound = pygame.mixer.Sound('res/easter_egg.mp3')
gate_close = pygame.mixer.Sound("res/gate_close.ogg")


def animate_text(text):
    for char in text:
        print(char, end='', flush=True)
        sample.play()
        wait(0.03)

def animate_text2(text):
    for char in text:
        print(char, end='', flush=True)
        sample.play()
        wait(0.07)

def clear():
    if os.name == 'nt':
        _ = os.system('cls')

    else:
        _ = os.system('clear')

def easter_egg():
    music.stop()
    easter_egg_sound.play()
    print('ААААААА', end='', flush=True)
    wait(0.4)
    print(' ПОСХАЛКО!!!', end='', flush=True)
    wait(0.9)
    print(' В НИКЕ ПОСХАЛКО!!', end='', flush=True)
    wait(1.5)
    print(' ВКЛЮЧАЙТЕ ВЕНТИЛЯТОРЫ!!!', end='', flush=True)
    wait(1.2)
    print('\rПОСХАЛКО                                                                  \n', end='', flush=True)
    gate_close.play()
    music.play()
clear()
text = "Привіт, "
animate_text(text)
wait(0.8)
text = "як справи?"
animate_text(text)
wait(2)
clear()
wait(0.45)
def menu():
    text = "Виберіть "
    animate_text(text)
    wait(0.4)
    text = "програму:"
    animate_text(text)
    print('\n')
    wait(0.8)
    print("      [0] *NEW* ПРОГРАМА ДО ДОМАШНЬОГО ЗАВДАННЯ")
    gate_close.play()
    print('\n                 (оновлено 02.06.2024)')
    wait(0.6)

    choose = input('  Ваш вибір: ')

    wait(0.3)
    clear()
    if choose == '0':
        music.stop()
        gate_close.play()
        music.play()
        def program_1():
            wait(3)
            animate_text2("1.1 - Використання if, elif, else.")
            wait(2)
            clear()
            wait(0.45)
            animate_text2("Виберіть день неділі:")
            wait(0.4)
            print('\n')
            int1 = input('Виберіть день неділі (1-7) ')
            wait(0.45)
            clear()
            animate_text2("Ви вибрали:")
            print('\n')
            wait(1)
            if int1 == '1': print('Понеділок')
            elif int1 == '2': print('Вівторок')
            elif int1 == '3': print('Середа')
            elif int1 == '4': print('Четвер')
            elif int1 == '5': print("П'ятниця")
            elif int1 == '6': print('Субота')
            elif int1 == '7': print('Неділя')
            elif int1 == '1488': easter_egg()
            else: print('Вибрано неправильне значення')
            gate_close.play()
            wait(3)
            input('Натисніть ANY KEY...')
            clear()
            gate_close.play()
            wait(1)
            animate_text2("1.2 - Використання if, elif, else.")
            wait(2)
            clear()
            wait(0.45)
            animate_text2("Виберіть місяць (1-12):")
            int1 = input(' ')
            clear()
            wait(0.45)
            animate_text2("Ви вибрали:")
            print('\n')
            wait(1)
            if int1 == '1': print('Січень')
            elif int1 == '2': print('Лютий')
            elif int1 == '3': print('Березень')
            elif int1 == '4': print('Квітень')
            elif int1 == '5': print("Травень")
            elif int1 == '6': print('Червень')
            elif int1 == '7': print('Липень')
            elif int1 == '8': print('Серпень')
            elif int1 == '9': print('Вересень')
            elif int1 == '10': print("Жовтень")
            elif int1 == '11': print('Листопад')
            elif int1 == '12': print('Грудень')
            elif int1 == '1488': easter_egg()
            else: print('Вибрано неправильне значення')
            gate_close.play()
            wait(3)
            input('Натисніть ANY KEY...')
            clear()
            gate_close.play()
            wait(1)
            animate_text2("2 - Використання if (розумний метод)")
            wait(2)
            clear()
            wait(0.45)
            animate_text2("Введіть число: ")
            int1 = int(input())
            wait(0.45)
            clear()
            animate_text2("Число ")
            wait(1)
            animate_text2("позитивне" if int1 > 0 else "негативне")
            wait(2)
            input('\nНатисніть ANY KEY...')
            clear()
            gate_close.play()
            wait(1)
            animate_text2("3 - Використання if (ще розумніший метод)")
            wait(2)
            clear()
            wait(0.45)
            animate_text2("Введіть число: ")
            int1 = int(input())
            wait(0.45)
            animate_text2("\nВведіть друге число: ")
            int2 = int(input())
            wait(0.45)
            clear()
            animate_text2("Результат:")
            wait(1)
            print('Числа парні') if int1 == int2 else print(f'\n{int1}\n{int2}') if int1 > int2 else print(f'\n{int2}\n{int1}')
            gate_close.play()
            wait(2)
            print('\n')
            animate_text2("Бажаєте почати знову?")
            wait(0.4)
            ans = input(' [y/n] ')
            if ans == 'y':
                wait(0.4)
                clear()
                gate_close.play()
                program_1()
            elif ans == 'Y':
                wait(0.4)
                clear()
                gate_close.play()
                program_1()

            else:
                clear()
                music.stop()
                gate_close.play()
                wait(1)
                menu()
        program_1()
    else:
        clear()
        music.stop()
        gate_close.play()
        wait(1)
        menu()





menu()
